//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "device")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Option<i32>,
    #[sea_orm(column_type = "Text", nullable)]
    pub name: Option<String>,
    #[sea_orm(column_name = "allUsers")]
    pub all_users: Option<bool>,
    pub lockout: Option<i32>,
    #[sea_orm(column_type = "Text", nullable)]
    pub lockout_start: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub lockout_end: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
