//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "device")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i64,
    #[sea_orm(column_type = "Text", nullable)]
    pub name: Option<String>,
    #[sea_orm(column_name = "allUsers")]
    pub all_users: Option<bool>,
    pub lockout: Option<i32>,
    #[sea_orm(column_type = "Text", nullable)]
    pub lockout_start: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub lockout_end: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::device_access::Entity")]
    DeviceAccess,
}

impl Related<super::device_access::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DeviceAccess.def()
    }
}

impl Related<super::user::Entity> for Entity {
    fn to() -> RelationDef {
        super::device_access::Relation::User.def()
    }

    fn via() -> Option<RelationDef> {
        Some(super::device_access::Relation::Device.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
