//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

pub use super::device::Entity as Device;
pub use super::device_access::Entity as DeviceAccess;
pub use super::log::Entity as Log;
pub use super::newuser::Entity as Newuser;
pub use super::user::Entity as User;
